/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VendorFrame.java
 *
 * Created on Oct 5, 2013, 8:43:03 PM
 */
package ta.app.frame.sistem;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ta.util.orm.MasterQuery;
import ta.util.orm.mapping.Vendor;

/**
 *
 * @author Sahal
 */
public class VendorFrame extends javax.swing.JInternalFrame {

    private final DefaultListModel vendorModel = new DefaultListModel();
    private List<Vendor> listVendor;
    private final MasterQuery<Vendor> queryVendor = new MasterQuery<Vendor>();

    /**
     * Creates new form VendoFrame
     */
    public VendorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vendorList = new javax.swing.JList();
        namaVendorTxt = new javax.swing.JTextField();
        kodeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        teleponTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        hapusBtn = new javax.swing.JButton();
        simpanBtn = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Data Vendor");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Vendor"));

        vendorList.setModel(vendorModel);
        vendorList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        vendorList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vendorListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(vendorList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel2.setText("Kode Vendor");

        jLabel1.setText("Nama Vendor");

        jLabel3.setText("Telepon");

        jLabel4.setText("E-Mail");

        alamatTxt.setColumns(20);
        alamatTxt.setRows(5);
        jScrollPane2.setViewportView(alamatTxt);

        jLabel5.setText("Alamat");

        hapusBtn.setText("Hapus");
        hapusBtn.setEnabled(false);
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teleponTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(namaVendorTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpanBtn)
                        .addGap(18, 18, 18)
                        .addComponent(hapusBtn)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaVendorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teleponTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapusBtn)
                            .addComponent(simpanBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        String msg = "Perubahan data vendor ";
        boolean action = false, result = false;

        if (kodeTxt.getText().isEmpty() || namaVendorTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isikan terlebih dahulu Kode dan Nama Vendor", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            if (kodeTxt.getText().length() <= 5 && namaVendorTxt.getText().length() <= 50) {
                Vendor vendor = queryVendor.detail("Vendor", "kode", kodeTxt.getText());

                if (vendor == null) {
                    vendor = new Vendor();
                    vendor.setIdVendor(0);
                }

                vendor.setKode(kodeTxt.getText());
                vendor.setNama(namaVendorTxt.getText());
                vendor.setTelepon(teleponTxt.getText());
                vendor.setEmail(emailTxt.getText());
                vendor.setAlamat(alamatTxt.getText());

                if (kodeTxt.isEditable()) {
                    if (vendor.getIdVendor() == 0) {
                        action = queryVendor.action(vendor, MasterQuery.ADD);
                        result = true;
                    } else {
                        JOptionPane.showMessageDialog(this, "Vendor dengan Kode [" + vendor.getKode() + "] sudah terdaftar", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    action = queryVendor.action(vendor, MasterQuery.UPDATE);
                    result = true;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Jumlah huruf untuk Kode atau Nama Vendor melebihi batas ketentuan", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }

        if (result) {
            JOptionPane.showMessageDialog(this, msg + ((action) ? "berhasil " : "gagal ") + "diproses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }

        fill();
        defaultView();
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        String name = namaVendorTxt.getText();
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data pengguna [" + name + "] ?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.OK_OPTION) {
            Vendor vendor = queryVendor.detail("Vendor", "kode", kodeTxt.getText());

            if (vendor != null) {
                boolean action = queryVendor.action(vendor, MasterQuery.DELETE);
                JOptionPane.showMessageDialog(this, "Vendor [" + name + "] " + ((action) ? "berhasil " : "gagal ") + "dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                fill();
            }
        }

        defaultView();
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void vendorListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vendorListValueChanged
        if (vendorList.getSelectedValue() != null) {
            if (vendorList.getSelectedValue().equals("[Tambah Vendor Baru]")) {
                defaultView();
            } else {
                Vendor vendor = listVendor.get(vendorList.getSelectedIndex());
                kodeTxt.setEditable(false);
                hapusBtn.setEnabled(true);
                kodeTxt.setText(vendor.getKode());
                namaVendorTxt.setText(vendor.getNama());
                teleponTxt.setText(vendor.getTelepon());
                emailTxt.setText(vendor.getEmail());
                alamatTxt.setText(vendor.getAlamat());
                kodeTxt.transferFocus();
            }
        }
    }//GEN-LAST:event_vendorListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kodeTxt;
    private javax.swing.JTextField namaVendorTxt;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTextField teleponTxt;
    private javax.swing.JList vendorList;
    // End of variables declaration//GEN-END:variables

    public void fill() {
        vendorModel.clear();
        listVendor = queryVendor.getListData("Vendor");

        for (Vendor vendor : listVendor) {
            vendorModel.addElement(vendor.getKode());
        }

        vendorModel.addElement("[Tambah Vendor Baru]");
        vendorList.transferFocus();
    }

    private void defaultView() {
        kodeTxt.setEditable(true);
        hapusBtn.setEnabled(false);
        kodeTxt.setText("");
        namaVendorTxt.setText("");
        teleponTxt.setText("");
        emailTxt.setText("");
        alamatTxt.setText("");
        vendorList.setSelectedIndex(listVendor.size());
        vendorList.transferFocus();
    }
}
