/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Master.java
 *
 * Created on Oct 5, 2013, 7:48:16 PM
 */
package ta.app;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import ta.app.frame.alat.InputFrame;
import ta.app.frame.alat.LihatFrame;
import ta.app.frame.alat.UbahFrame;
import ta.app.frame.kalibrasi.BulanFrame;
import ta.app.frame.kalibrasi.HasilFrame;
import ta.app.frame.kalibrasi.TahunFrame;
import ta.app.frame.laporan.MingguFrame;
import ta.app.frame.laporan.OrderFrame;
import ta.app.frame.laporan.StokFrame;
import ta.app.frame.order.DaftarFrame;
import ta.app.frame.order.PermohonanFrame;
import ta.app.frame.order.ProsesFrame;
import ta.app.frame.order.SetujuFrame;
import ta.app.frame.sistem.MasukFrame;
import ta.app.frame.sistem.OtorisasiFrame;
import ta.app.frame.sistem.PenggunaFrame;
import ta.app.frame.sistem.VendoFrame;
import ta.util.orm.mapping.HakAkses;

/**
 *
 * @author Sahal
 */
public class Master extends javax.swing.JFrame {
    //MenuSistem

    private JInternalFrame loginFrame, otorisasiFrame, penggunaFrame, vendorFrame;
    //Menu Alat Ukur
    private JInternalFrame inputFrame, lihatFrame, ubahFrame;
    //Menu Kalibrasi
    private JInternalFrame bulanFrame, hasilFrame, tahunFrame;
    //Menu Order
    private JInternalFrame daftarFrame, permohonanFrame, prosesFrame, setujuFrame;
    //MenuLaporan
    private JInternalFrame lapBulanFrame, mingguFrame, orderFrame, stokFrame;
    private HakAkses activeUser;

    /** Creates new form Master */
    public Master() {
        initComponents();
        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterPane = new javax.swing.JDesktopPane();
        Transaksi = new javax.swing.JMenuBar();
        sistemMenu = new javax.swing.JMenu();
        masukItem = new javax.swing.JMenuItem();
        keluarItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        vendorItem = new javax.swing.JMenuItem();
        penggunaItem = new javax.swing.JMenuItem();
        otorisasiItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        tutupItem = new javax.swing.JMenuItem();
        alatMenu = new javax.swing.JMenu();
        inputItem = new javax.swing.JMenuItem();
        lihatItem = new javax.swing.JMenuItem();
        ubahItem = new javax.swing.JMenuItem();
        kalibrasiMenu = new javax.swing.JMenu();
        kalibrasiItem = new javax.swing.JMenu();
        jBulanItem = new javax.swing.JMenuItem();
        jTahunItem = new javax.swing.JMenuItem();
        hasilItem = new javax.swing.JMenuItem();
        orderMenu = new javax.swing.JMenu();
        permohonanItem = new javax.swing.JMenuItem();
        prosesItem = new javax.swing.JMenuItem();
        setujuItem = new javax.swing.JMenuItem();
        daftarItem = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        lapStokItem = new javax.swing.JMenuItem();
        lapKalibrasiItem = new javax.swing.JMenu();
        lapMingguItem = new javax.swing.JMenuItem();
        lapBulanItem = new javax.swing.JMenuItem();
        lapOrderItem = new javax.swing.JMenuItem();
        infoMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Sistem Informasi Alat Ukur");

        sistemMenu.setText("Sistem");

        masukItem.setText("Masuk");
        masukItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukItemActionPerformed(evt);
            }
        });
        sistemMenu.add(masukItem);

        keluarItem.setText("Keluar");
        keluarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarItemActionPerformed(evt);
            }
        });
        sistemMenu.add(keluarItem);
        sistemMenu.add(jSeparator1);

        vendorItem.setText("Data Vendor");
        vendorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorItemActionPerformed(evt);
            }
        });
        sistemMenu.add(vendorItem);

        penggunaItem.setText("Data Pengguna");
        penggunaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaItemActionPerformed(evt);
            }
        });
        sistemMenu.add(penggunaItem);

        otorisasiItem.setText("Otorisasi");
        otorisasiItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otorisasiItemActionPerformed(evt);
            }
        });
        sistemMenu.add(otorisasiItem);
        sistemMenu.add(jSeparator2);

        tutupItem.setText("Tutup");
        tutupItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupItemActionPerformed(evt);
            }
        });
        sistemMenu.add(tutupItem);

        Transaksi.add(sistemMenu);

        inputItem.setText("Input Data");
        alatMenu.add(inputItem);

        lihatItem.setText("Lihat Data");
        alatMenu.add(lihatItem);

        ubahItem.setText("Ubah Data");
        alatMenu.add(ubahItem);

        Transaksi.add(alatMenu);

        kalibrasiMenu.setText("Kalibrasi");

        kalibrasiItem.setText("Jadwal Kalibrasi");

        jBulanItem.setText("Jadwal  Bulanan");
        kalibrasiItem.add(jBulanItem);

        jTahunItem.setText("Jadwal Tahunan");
        kalibrasiItem.add(jTahunItem);

        kalibrasiMenu.add(kalibrasiItem);

        hasilItem.setText("Hasil Kalibrasi");
        kalibrasiMenu.add(hasilItem);

        Transaksi.add(kalibrasiMenu);

        orderMenu.setText("Order");

        permohonanItem.setText("Permohonan");
        orderMenu.add(permohonanItem);

        prosesItem.setText("Proses");
        orderMenu.add(prosesItem);

        setujuItem.setText("Persetujuan");
        orderMenu.add(setujuItem);

        daftarItem.setText("Daftar Order");
        orderMenu.add(daftarItem);

        Transaksi.add(orderMenu);

        laporanMenu.setText("Laporan");

        lapStokItem.setText("Laporan Stok");
        laporanMenu.add(lapStokItem);

        lapKalibrasiItem.setText("Laporan Kalibrasi");

        lapMingguItem.setText("Laporan Mingguan");
        lapKalibrasiItem.add(lapMingguItem);

        lapBulanItem.setText("Laporan Bulanan");
        lapKalibrasiItem.add(lapBulanItem);

        laporanMenu.add(lapKalibrasiItem);

        lapOrderItem.setText("Laporan Order");
        laporanMenu.add(lapOrderItem);

        Transaksi.add(laporanMenu);

        infoMenu.setText("Informasi");
        Transaksi.add(infoMenu);

        setJMenuBar(Transaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterPane, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukItemActionPerformed
        kondisiAwal();
        closeAllFrame();
        MasukFrame loginWindow = (MasukFrame) loginFrame;
        loginWindow.clear();
    }//GEN-LAST:event_masukItemActionPerformed

    private void keluarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarItemActionPerformed
        masukItemActionPerformed(evt);
    }//GEN-LAST:event_keluarItemActionPerformed

    private void vendorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorItemActionPerformed
        vendorFrame.show();
    }//GEN-LAST:event_vendorItemActionPerformed

    private void penggunaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaItemActionPerformed
       penggunaFrame.show();
    }//GEN-LAST:event_penggunaItemActionPerformed

    private void otorisasiItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otorisasiItemActionPerformed
        otorisasiFrame.show();
    }//GEN-LAST:event_otorisasiItemActionPerformed

    private void tutupItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_tutupItemActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Master().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Transaksi;
    private javax.swing.JMenu alatMenu;
    private javax.swing.JMenuItem daftarItem;
    private javax.swing.JMenuItem hasilItem;
    private javax.swing.JMenu infoMenu;
    private javax.swing.JMenuItem inputItem;
    private javax.swing.JMenuItem jBulanItem;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jTahunItem;
    private javax.swing.JMenu kalibrasiItem;
    private javax.swing.JMenu kalibrasiMenu;
    private javax.swing.JMenuItem keluarItem;
    private javax.swing.JMenuItem lapBulanItem;
    private javax.swing.JMenu lapKalibrasiItem;
    private javax.swing.JMenuItem lapMingguItem;
    private javax.swing.JMenuItem lapOrderItem;
    private javax.swing.JMenuItem lapStokItem;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenuItem lihatItem;
    private javax.swing.JDesktopPane masterPane;
    private javax.swing.JMenuItem masukItem;
    private javax.swing.JMenu orderMenu;
    private javax.swing.JMenuItem otorisasiItem;
    private javax.swing.JMenuItem penggunaItem;
    private javax.swing.JMenuItem permohonanItem;
    private javax.swing.JMenuItem prosesItem;
    private javax.swing.JMenuItem setujuItem;
    private javax.swing.JMenu sistemMenu;
    private javax.swing.JMenuItem tutupItem;
    private javax.swing.JMenuItem ubahItem;
    private javax.swing.JMenuItem vendorItem;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setWindowsTheme();
        initInternalFrame();
        kondisiAwal();
    }

    private void setWindowsTheme() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Master.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Master.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Master.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Master.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initInternalFrame() {
        //Menu Sistem
        loginFrame = new MasukFrame(this);
        otorisasiFrame = new OtorisasiFrame();
        penggunaFrame = new PenggunaFrame();
        vendorFrame = new VendoFrame();
        //menu alat ukur
        inputFrame = new InputFrame();
        lihatFrame = new LihatFrame();
        ubahFrame = new UbahFrame();
        //menu kalibrasi
        bulanFrame = new BulanFrame();
        hasilFrame = new HasilFrame();
        tahunFrame = new TahunFrame();
        //menu order
        daftarFrame = new DaftarFrame();
        permohonanFrame = new PermohonanFrame();
        prosesFrame = new ProsesFrame();
        setujuFrame = new SetujuFrame();
        //menu laporan
        lapBulanFrame = new ta.app.frame.laporan.BulanFrame();
        mingguFrame = new MingguFrame();
        orderFrame = new OrderFrame();
        stokFrame = new StokFrame();
        masterPane.add(loginFrame);
        masterPane.add(otorisasiFrame);
        masterPane.add(penggunaFrame);
        masterPane.add(vendorFrame);
        masterPane.add(inputFrame);
        masterPane.add(lihatFrame);
        masterPane.add(ubahFrame);
        masterPane.add(bulanFrame);
        masterPane.add(hasilFrame);
        masterPane.add(tahunFrame);
        masterPane.add(daftarFrame);
        masterPane.add(permohonanFrame);
        masterPane.add(prosesFrame);
        masterPane.add(setujuFrame);
        masterPane.add(lapBulanFrame);
        masterPane.add(mingguFrame);
        masterPane.add(orderFrame);
        masterPane.add(stokFrame);

    }

    private void kondisiAwal() {
        loginFrame.show();
        keluarItem.setEnabled(false);
        vendorItem.setEnabled(false);
        penggunaItem.setEnabled(false);
        otorisasiItem.setEnabled(false);
        alatMenu.setEnabled(false);
        kalibrasiMenu.setEnabled(false);
        orderMenu.setEnabled(false);
        laporanMenu.setEnabled(false);
    }

    public void otorisasi(HakAkses hakAkses) {
        activeUser = hakAkses;
        keluarItem.setEnabled(true);
        orderMenu.setEnabled(true);

        if (activeUser.getOtorisasi().equals("admin")) {
            vendorItem.setEnabled(true);
            penggunaItem.setEnabled(true);
            otorisasiItem.setEnabled(true);
            alatMenu.setEnabled(true);
            kalibrasiMenu.setEnabled(true);
            laporanMenu.setEnabled(true);
            inputItem.setEnabled(true);
            ubahItem.setEnabled(true);
            prosesItem.setEnabled(true);
            setujuItem.setEnabled(true);
            permohonanItem.setEnabled(true);
        } else if (activeUser.getOtorisasi().equals("inspector")) {
            vendorItem.setEnabled(true);
            penggunaItem.setEnabled(true);
            alatMenu.setEnabled(true);
            kalibrasiMenu.setEnabled(true);
            laporanMenu.setEnabled(true);
            inputItem.setEnabled(true);
            ubahItem.setEnabled(true);
            prosesItem.setEnabled(true);
            setujuItem.setEnabled(true);
            permohonanItem.setEnabled(true);
        } else if (activeUser.getOtorisasi().equals("produksi")) {
            vendorItem.setEnabled(true);
            penggunaItem.setEnabled(true);
            alatMenu.setEnabled(true);
            inputItem.setEnabled(false);
            ubahItem.setEnabled(false);
            prosesItem.setEnabled(false);
            setujuItem.setEnabled(false);
        } else if (activeUser.getOtorisasi().equals("pimpinan")) {
            laporanMenu.setEnabled(true);
            prosesItem.setEnabled(false);
            setujuItem.setEnabled(true);
            permohonanItem.setEnabled(false);
        }

    }
    private void closeAllFrame(){
        otorisasiFrame.setVisible(false);
        penggunaFrame.setVisible(false);
        vendorFrame.setVisible(false);
        daftarFrame.setVisible(false);
        permohonanFrame.setVisible(false);
        prosesFrame.setVisible(false);
        setujuFrame.setVisible(false);
        bulanFrame.setVisible(false);
        mingguFrame.setVisible(false);
        orderFrame.setVisible(false);
        stokFrame.setVisible(false);
        lapBulanFrame.setVisible(false);
        hasilFrame.setVisible(false);
        tahunFrame.setVisible(false);
        inputFrame.setVisible(false);
        lihatFrame.setVisible(false);
        ubahFrame.setVisible(false);
    }
}
