/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputFrame.java
 *
 * Created on Oct 5, 2013, 8:46:19 PM
 */
package ta.app.frame.alat;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ta.util.orm.MasterQuery;
import ta.util.orm.mapping.AlatUkur;
import ta.util.orm.mapping.Vendor;

/**
 *
 * @author Sahal
 */
public class InputFrame extends javax.swing.JInternalFrame {

    private final DefaultListModel modelAlat = new DefaultListModel();
    private final DefaultComboBoxModel modelVendor = new DefaultComboBoxModel();
    private List<AlatUkur> listAlat;
    private List<Vendor> listVendors;
    private final MasterQuery<AlatUkur> queryAlat = new MasterQuery<AlatUkur>();
    private final MasterQuery<Vendor> queryVendor = new MasterQuery<Vendor>();

    /**
     * Creates new form InputFrame
     */
    public InputFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        kodeLbl = new javax.swing.JLabel();
        kodeTxt = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        alatTxt = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        standarTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modelTxt = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomorTxt = new javax.swing.JSpinner();
        lokasiTxt = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        vendorTxt = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tanggalTxt = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        hapusBtn = new javax.swing.JButton();
        batalBtn = new javax.swing.JButton();
        simpanBtn = new javax.swing.JButton();
        jumlahTxt = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        tipeTxt = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        serialTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cariList = new javax.swing.JList();
        cariTxt = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Input Data Alat Ukur");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        kodeLbl.setText("MKMG1-");

        kodeTxt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel1.setText("Kode Alat");

        alatTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vernier Caliper", "Micrometer", "Holtest", "Dial Test Indicator", "Bore Gauge", "Ring Gauge", "Thread Gauge", "Snap Gauge", "Width Gauge", "Plug Gauge" }));

        jLabel2.setText("Nama Alat");

        jLabel4.setText("Standar");

        modelTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mitsubishi", "Suzuki" }));

        jLabel6.setText("Model");

        jLabel10.setText("-");

        nomorTxt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        lokasiTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kalibrasi Room", "CS", "CR", "CH", "CB", "CM" }));

        jLabel3.setText("Lokasi");

        vendorTxt.setModel(modelVendor);

        jLabel5.setText("Vendor");

        tanggalTxt.setDateFormatString("dd MMMM yyyy");

        jLabel8.setText("Tanggal Pembelian");

        hapusBtn.setText("Hapus");
        hapusBtn.setEnabled(false);
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        jumlahTxt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel7.setText("Jumlah");

        tipeTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alat Ukur", "Alat Inspeksi" }));

        jLabel11.setText("Tipe");

        jLabel12.setText("No. Seri");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(kodeLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kodeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                                    .addComponent(tipeTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(serialTxt)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(simpanBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(batalBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hapusBtn))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(standarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(alatTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(vendorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lokasiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nomorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeLbl)
                    .addComponent(kodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lokasiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(nomorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tanggalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusBtn)
                    .addComponent(batalBtn)
                    .addComponent(simpanBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cariList.setModel(modelAlat);
        cariList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cariList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cariListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(cariList);

        cariTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lihat Alat Ukur Berdasarkan Nama", "Vernier Caliper", "Micrometer", "Holtest", "Dial Test Indicator", "Bore Gauge", "Ring Gauge", "Thread Gauge", "Snap Gauge", "Width Gauge", "Plug Gauge" }));
        cariTxt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cariTxtItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cariTxt, 0, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_cariListValueChanged
        if (cariList.getSelectedValue() != null) {
            AlatUkur alatUkur = listAlat.get(cariList.getSelectedIndex());
            Vendor vendor = queryVendor.detail("Vendor", "idVendor", String.valueOf(alatUkur.getVendor().getIdVendor()));
            kodeTxt.setEnabled(false);
            hapusBtn.setEnabled(true);
            int kode = Integer.parseInt(alatUkur.getKode().replaceFirst(kodeLbl.getText(), ""));
            kodeTxt.setValue(kode);
            alatTxt.setSelectedItem(alatUkur.getNama());
            standarTxt.setText(alatUkur.getStandar());
            modelTxt.setSelectedItem(alatUkur.getModel());
            String lokasi[] = alatUkur.getLokasi().split("-");
            int lokasinya = (lokasi.length > 1) ? Integer.parseInt(lokasi[1]) : 0;
            lokasiTxt.setSelectedItem(lokasi[0]);
            nomorTxt.setValue(lokasinya);
            tanggalTxt.setDate(alatUkur.getTanggalBeli());
            tipeTxt.setSelectedItem(alatUkur.getTipe());
            serialTxt.setText(alatUkur.getSerial());
            jumlahTxt.setValue(alatUkur.getJumlah());
            vendorTxt.setSelectedItem(vendor.getNama());
            kodeTxt.transferFocus();
        }
    }//GEN-LAST:event_cariListValueChanged

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        saving();
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        defaultView();
        fill();
    }//GEN-LAST:event_batalBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        String item = kodeLbl.getText() + kodeTxt.getValue();
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data alat ukur [" + item + "] ?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.OK_OPTION) {
            AlatUkur alatUkur = queryAlat.detail("AlatUkur", "kode", item);

            if (alatUkur != null) {
                boolean action = queryAlat.action(alatUkur, MasterQuery.DELETE);
                JOptionPane.showMessageDialog(this, "Alat Ukur [" + item + "] " + ((action) ? "berhasil " : "gagal ") + "dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        defaultView();
        fill();
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void cariTxtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cariTxtItemStateChanged
        if (cariTxt.getSelectedItem() != null) {
            if (!cariTxt.getSelectedItem().equals("Lihat Alat Ukur Berdasarkan Nama")) {
                find();
            } else {
                fill();
            }
        }
    }//GEN-LAST:event_cariTxtItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox alatTxt;
    private javax.swing.JButton batalBtn;
    private javax.swing.JList cariList;
    private javax.swing.JComboBox cariTxt;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jumlahTxt;
    private javax.swing.JLabel kodeLbl;
    private javax.swing.JSpinner kodeTxt;
    private javax.swing.JComboBox lokasiTxt;
    private javax.swing.JComboBox modelTxt;
    private javax.swing.JSpinner nomorTxt;
    private javax.swing.JTextField serialTxt;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTextField standarTxt;
    private com.toedter.calendar.JDateChooser tanggalTxt;
    private javax.swing.JComboBox tipeTxt;
    private javax.swing.JComboBox vendorTxt;
    // End of variables declaration//GEN-END:variables

    public void fill() {
        modelAlat.clear();
        modelVendor.removeAllElements();
        listVendors = queryVendor.getListData("Vendor");
        listAlat = queryAlat.getListData("AlatUkur");

        for (Vendor vendor : listVendors) {
            modelVendor.addElement(vendor.getNama());
        }

        for (AlatUkur alatUkur : listAlat) {
            modelAlat.addElement(alatUkur.getKode());
        }

        cariList.transferFocus();
    }

    private void defaultView() {
        kodeTxt.setEnabled(true);
        hapusBtn.setEnabled(false);
        cariTxt.setSelectedIndex(0);
        kodeTxt.setValue(0);
        alatTxt.setSelectedIndex(0);
        standarTxt.setText("");
        modelTxt.setSelectedIndex(0);
        lokasiTxt.setSelectedIndex(0);
        nomorTxt.setValue(0);
        tanggalTxt.setDate(null);
        tipeTxt.setSelectedIndex(0);
        serialTxt.setText("");
        jumlahTxt.setValue(0);
        cariList.transferFocus();

        if (modelVendor.getSize() > 0) {
            vendorTxt.setSelectedIndex(0);
        }
    }

    private void saving() {
        String msg = "Perubahan data Alat Ukur ";
        boolean action = false, result = false;

        if (serialTxt.getText().isEmpty() || standarTxt.getText().isEmpty() || tanggalTxt.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Mohon isikan terlebih dahulu Nomor Seri, Standar dan Tanggal Pembelian", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            if (serialTxt.getText().length() <= 45 && standarTxt.getText().length() <= 45) {
                AlatUkur alatUkur = queryAlat.detail("AlatUkur", "kode", kodeLbl.getText() + kodeTxt.getValue());

                if (alatUkur == null) {
                    alatUkur = new AlatUkur();
                    alatUkur.setIdAlatUkur(0);
                }

                String letakLokasi = (String.valueOf(lokasiTxt.getSelectedItem()).equals("Kalibrasi Room")) ? "" : "-" + nomorTxt.getValue();
                alatUkur.setKode(kodeLbl.getText() + kodeTxt.getValue());
                alatUkur.setTipe(String.valueOf(tipeTxt.getSelectedItem()));
                alatUkur.setSerial(serialTxt.getText());
                alatUkur.setNama(String.valueOf(alatTxt.getSelectedItem()));
                alatUkur.setStandar(standarTxt.getText());
                alatUkur.setModel(String.valueOf(modelTxt.getSelectedItem()));
                alatUkur.setLokasi(String.valueOf(lokasiTxt.getSelectedItem()) + letakLokasi);
                alatUkur.setVendor(queryVendor.detail("Vendor", "nama", String.valueOf(vendorTxt.getSelectedItem())));
                alatUkur.setTanggalBeli(tanggalTxt.getDate());
                alatUkur.setJumlah(Integer.parseInt(String.valueOf(jumlahTxt.getValue())));

                if (kodeTxt.isEnabled()) {
                    if (alatUkur.getIdAlatUkur() == 0) {
                        action = queryAlat.action(alatUkur, MasterQuery.ADD);
                        result = true;
                    } else {
                        JOptionPane.showMessageDialog(this, "Alat Ukur dengan Kode [" + alatUkur.getKode() + "] sudah terdaftar", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    action = queryAlat.action(alatUkur, MasterQuery.UPDATE);
                    result = true;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Jumlah huruf untuk Nomor Seri atau Standar melebihi batas ketentuan", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }

        if (result) {
            JOptionPane.showMessageDialog(this, msg + ((action) ? "berhasil " : "gagal ") + "diproses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }

        fill();
        defaultView();
    }

    private void find() {
        modelAlat.clear();
        listAlat = queryAlat.getListData("AlatUkur", "nama", String.valueOf(cariTxt.getSelectedItem()));

        for (AlatUkur alatUkur : listAlat) {
            modelAlat.addElement(alatUkur.getKode());
        }

        cariList.transferFocus();
    }

}
