package ta.util.orm.mapping;
// Generated Jan 31, 2014 4:08:54 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Akses generated by hbm2java
 */
@Entity
@Table(name="akses"
    ,catalog="`TA-SAHAL`"
)
public class Akses  implements java.io.Serializable {


     private Integer idAkses;
     private Pengguna pengguna;
     private String sandi;
     private String hak;

    public Akses() {
    }

    public Akses(Pengguna pengguna, String sandi, String hak) {
       this.pengguna = pengguna;
       this.sandi = sandi;
       this.hak = hak;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_akses", unique=true, nullable=false)
    public Integer getIdAkses() {
        return this.idAkses;
    }
    
    public void setIdAkses(Integer idAkses) {
        this.idAkses = idAkses;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pengguna", nullable=false)
    public Pengguna getPengguna() {
        return this.pengguna;
    }
    
    public void setPengguna(Pengguna pengguna) {
        this.pengguna = pengguna;
    }

    
    @Column(name="sandi", nullable=false, length=12)
    public String getSandi() {
        return this.sandi;
    }
    
    public void setSandi(String sandi) {
        this.sandi = sandi;
    }

    
    @Column(name="hak", nullable=false, length=9)
    public String getHak() {
        return this.hak;
    }
    
    public void setHak(String hak) {
        this.hak = hak;
    }




}


