package ta.util.orm.mapping;
// Generated Jan 31, 2014 3:09:33 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataHasil generated by hbm2java
 */
@Entity
@Table(name="data_hasil"
    ,catalog="`TA-SAHAL`"
)
public class DataHasil  implements java.io.Serializable {


     private Integer idDataHasil;
     private String posisiAlat;
     private String deviasi;
     private String type;
     private Set<HasilKalibrasi> hasilKalibrasis = new HashSet<HasilKalibrasi>(0);

    public DataHasil() {
    }

	
    public DataHasil(String posisiAlat, String deviasi, String type) {
        this.posisiAlat = posisiAlat;
        this.deviasi = deviasi;
        this.type = type;
    }
    public DataHasil(String posisiAlat, String deviasi, String type, Set<HasilKalibrasi> hasilKalibrasis) {
       this.posisiAlat = posisiAlat;
       this.deviasi = deviasi;
       this.type = type;
       this.hasilKalibrasis = hasilKalibrasis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_data_hasil", unique=true, nullable=false)
    public Integer getIdDataHasil() {
        return this.idDataHasil;
    }
    
    public void setIdDataHasil(Integer idDataHasil) {
        this.idDataHasil = idDataHasil;
    }

    
    @Column(name="posisi_alat", nullable=false, length=45)
    public String getPosisiAlat() {
        return this.posisiAlat;
    }
    
    public void setPosisiAlat(String posisiAlat) {
        this.posisiAlat = posisiAlat;
    }

    
    @Column(name="deviasi", nullable=false, length=45)
    public String getDeviasi() {
        return this.deviasi;
    }
    
    public void setDeviasi(String deviasi) {
        this.deviasi = deviasi;
    }

    
    @Column(name="type", nullable=false, length=6)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dataHasil")
    public Set<HasilKalibrasi> getHasilKalibrasis() {
        return this.hasilKalibrasis;
    }
    
    public void setHasilKalibrasis(Set<HasilKalibrasi> hasilKalibrasis) {
        this.hasilKalibrasis = hasilKalibrasis;
    }




}


