package ta.util.orm.mapping;
// Generated Jan 29, 2014 9:57:48 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataKalibrasi generated by hbm2java
 */
@Entity
@Table(name="data_kalibrasi"
    ,catalog="`TA-SAHAL`"
)
public class DataKalibrasi  implements java.io.Serializable {


     private Integer idDataKalibrasi;
     private JadwalKalibrasi jadwalKalibrasi;
     private String nomorLaporan;
     private String pelanggan;
     private String standar;
     private String metode;
     private String acuan;
     private String ketelitianGo;
     private String ketilitianNg;
     private Set<HasilKalibrasi> hasilKalibrasis = new HashSet<HasilKalibrasi>(0);

    public DataKalibrasi() {
    }

	
    public DataKalibrasi(JadwalKalibrasi jadwalKalibrasi, String nomorLaporan, String pelanggan, String standar, String acuan, String ketelitianGo, String ketilitianNg) {
        this.jadwalKalibrasi = jadwalKalibrasi;
        this.nomorLaporan = nomorLaporan;
        this.pelanggan = pelanggan;
        this.standar = standar;
        this.acuan = acuan;
        this.ketelitianGo = ketelitianGo;
        this.ketilitianNg = ketilitianNg;
    }
    public DataKalibrasi(JadwalKalibrasi jadwalKalibrasi, String nomorLaporan, String pelanggan, String standar, String metode, String acuan, String ketelitianGo, String ketilitianNg, Set<HasilKalibrasi> hasilKalibrasis) {
       this.jadwalKalibrasi = jadwalKalibrasi;
       this.nomorLaporan = nomorLaporan;
       this.pelanggan = pelanggan;
       this.standar = standar;
       this.metode = metode;
       this.acuan = acuan;
       this.ketelitianGo = ketelitianGo;
       this.ketilitianNg = ketilitianNg;
       this.hasilKalibrasis = hasilKalibrasis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_data_kalibrasi", unique=true, nullable=false)
    public Integer getIdDataKalibrasi() {
        return this.idDataKalibrasi;
    }
    
    public void setIdDataKalibrasi(Integer idDataKalibrasi) {
        this.idDataKalibrasi = idDataKalibrasi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jadwal_kalibrasi", nullable=false)
    public JadwalKalibrasi getJadwalKalibrasi() {
        return this.jadwalKalibrasi;
    }
    
    public void setJadwalKalibrasi(JadwalKalibrasi jadwalKalibrasi) {
        this.jadwalKalibrasi = jadwalKalibrasi;
    }

    
    @Column(name="nomor_laporan", nullable=false, length=45)
    public String getNomorLaporan() {
        return this.nomorLaporan;
    }
    
    public void setNomorLaporan(String nomorLaporan) {
        this.nomorLaporan = nomorLaporan;
    }

    
    @Column(name="pelanggan", nullable=false, length=65535)
    public String getPelanggan() {
        return this.pelanggan;
    }
    
    public void setPelanggan(String pelanggan) {
        this.pelanggan = pelanggan;
    }

    
    @Column(name="standar", nullable=false, length=65535)
    public String getStandar() {
        return this.standar;
    }
    
    public void setStandar(String standar) {
        this.standar = standar;
    }

    
    @Column(name="metode", length=45)
    public String getMetode() {
        return this.metode;
    }
    
    public void setMetode(String metode) {
        this.metode = metode;
    }

    
    @Column(name="acuan", nullable=false, length=45)
    public String getAcuan() {
        return this.acuan;
    }
    
    public void setAcuan(String acuan) {
        this.acuan = acuan;
    }

    
    @Column(name="ketelitian_go", nullable=false, length=50)
    public String getKetelitianGo() {
        return this.ketelitianGo;
    }
    
    public void setKetelitianGo(String ketelitianGo) {
        this.ketelitianGo = ketelitianGo;
    }

    
    @Column(name="ketilitian_ng", nullable=false, length=45)
    public String getKetilitianNg() {
        return this.ketilitianNg;
    }
    
    public void setKetilitianNg(String ketilitianNg) {
        this.ketilitianNg = ketilitianNg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dataKalibrasi")
    public Set<HasilKalibrasi> getHasilKalibrasis() {
        return this.hasilKalibrasis;
    }
    
    public void setHasilKalibrasis(Set<HasilKalibrasi> hasilKalibrasis) {
        this.hasilKalibrasis = hasilKalibrasis;
    }




}


