package ta.util.orm.mapping;
// Generated Oct 20, 2013 5:25:45 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HakAkses generated by hbm2java
 */
@Entity
@Table(name="hak_akses"
    ,catalog="skripsi"
)
public class HakAkses  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String password;
     private String otorisasi;

    public HakAkses() {
    }

    public HakAkses(String nama, String password, String otorisasi) {
       this.nama = nama;
       this.password = password;
       this.otorisasi = otorisasi;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nama", nullable=false, length=45)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="otorisasi", nullable=false, length=50)
    public String getOtorisasi() {
        return this.otorisasi;
    }
    
    public void setOtorisasi(String otorisasi) {
        this.otorisasi = otorisasi;
    }




}


