package ta.util.orm.mapping;
// Generated Jan 31, 2014 4:08:54 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HasilKalibrasi generated by hbm2java
 */
@Entity
@Table(name="hasil_kalibrasi"
    ,catalog="`TA-SAHAL`"
)
public class HasilKalibrasi  implements java.io.Serializable {


     private Integer idHasilKalibrasi;
     private DataKalibrasi dataKalibrasi;
     private DataHasil dataHasil;
     private String hasil;

    public HasilKalibrasi() {
    }

    public HasilKalibrasi(DataKalibrasi dataKalibrasi, DataHasil dataHasil, String hasil) {
       this.dataKalibrasi = dataKalibrasi;
       this.dataHasil = dataHasil;
       this.hasil = hasil;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_hasil_kalibrasi", unique=true, nullable=false)
    public Integer getIdHasilKalibrasi() {
        return this.idHasilKalibrasi;
    }
    
    public void setIdHasilKalibrasi(Integer idHasilKalibrasi) {
        this.idHasilKalibrasi = idHasilKalibrasi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="data_kalibrasi", nullable=false)
    public DataKalibrasi getDataKalibrasi() {
        return this.dataKalibrasi;
    }
    
    public void setDataKalibrasi(DataKalibrasi dataKalibrasi) {
        this.dataKalibrasi = dataKalibrasi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="data_hasil", nullable=false)
    public DataHasil getDataHasil() {
        return this.dataHasil;
    }
    
    public void setDataHasil(DataHasil dataHasil) {
        this.dataHasil = dataHasil;
    }

    
    @Column(name="hasil", nullable=false, length=3)
    public String getHasil() {
        return this.hasil;
    }
    
    public void setHasil(String hasil) {
        this.hasil = hasil;
    }




}


