package ta.util.orm.mapping;
// Generated Jan 31, 2014 4:08:54 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JadwalKalibrasi generated by hbm2java
 */
@Entity
@Table(name="jadwal_kalibrasi"
    ,catalog="`TA-SAHAL`"
)
public class JadwalKalibrasi  implements java.io.Serializable {


     private Integer idJadwalKalibrasi;
     private AlatUkur alatUkur;
     private Date tanggal;
     private String tempat;
     private Set<DataKalibrasi> dataKalibrasis = new HashSet<DataKalibrasi>(0);

    public JadwalKalibrasi() {
    }

	
    public JadwalKalibrasi(AlatUkur alatUkur, Date tanggal, String tempat) {
        this.alatUkur = alatUkur;
        this.tanggal = tanggal;
        this.tempat = tempat;
    }
    public JadwalKalibrasi(AlatUkur alatUkur, Date tanggal, String tempat, Set<DataKalibrasi> dataKalibrasis) {
       this.alatUkur = alatUkur;
       this.tanggal = tanggal;
       this.tempat = tempat;
       this.dataKalibrasis = dataKalibrasis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_jadwal_kalibrasi", unique=true, nullable=false)
    public Integer getIdJadwalKalibrasi() {
        return this.idJadwalKalibrasi;
    }
    
    public void setIdJadwalKalibrasi(Integer idJadwalKalibrasi) {
        this.idJadwalKalibrasi = idJadwalKalibrasi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="alat_ukur", nullable=false)
    public AlatUkur getAlatUkur() {
        return this.alatUkur;
    }
    
    public void setAlatUkur(AlatUkur alatUkur) {
        this.alatUkur = alatUkur;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="tanggal", nullable=false, length=10)
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }

    
    @Column(name="tempat", nullable=false, length=45)
    public String getTempat() {
        return this.tempat;
    }
    
    public void setTempat(String tempat) {
        this.tempat = tempat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jadwalKalibrasi")
    public Set<DataKalibrasi> getDataKalibrasis() {
        return this.dataKalibrasis;
    }
    
    public void setDataKalibrasis(Set<DataKalibrasi> dataKalibrasis) {
        this.dataKalibrasis = dataKalibrasis;
    }




}


