package ta.util.orm.mapping;
// Generated Jan 31, 2014 4:08:54 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pengguna generated by hbm2java
 */
@Entity
@Table(name="pengguna"
    ,catalog="`TA-SAHAL`"
)
public class Pengguna  implements java.io.Serializable {


     private Integer idPengguna;
     private String nama;
     private String nik;
     private String bagian;
     private String jabatan;
     private Set<Akses> akseses = new HashSet<Akses>(0);
     private Set<Po> pos = new HashSet<Po>(0);
     private Set<Pesanan> pesanans = new HashSet<Pesanan>(0);

    public Pengguna() {
    }

	
    public Pengguna(String nama, String nik, String bagian, String jabatan) {
        this.nama = nama;
        this.nik = nik;
        this.bagian = bagian;
        this.jabatan = jabatan;
    }
    public Pengguna(String nama, String nik, String bagian, String jabatan, Set<Akses> akseses, Set<Po> pos, Set<Pesanan> pesanans) {
       this.nama = nama;
       this.nik = nik;
       this.bagian = bagian;
       this.jabatan = jabatan;
       this.akseses = akseses;
       this.pos = pos;
       this.pesanans = pesanans;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_pengguna", unique=true, nullable=false)
    public Integer getIdPengguna() {
        return this.idPengguna;
    }
    
    public void setIdPengguna(Integer idPengguna) {
        this.idPengguna = idPengguna;
    }

    
    @Column(name="nama", nullable=false, length=20)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="nik", nullable=false, length=5)
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }

    
    @Column(name="bagian", nullable=false, length=11)
    public String getBagian() {
        return this.bagian;
    }
    
    public void setBagian(String bagian) {
        this.bagian = bagian;
    }

    
    @Column(name="jabatan", nullable=false, length=11)
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pengguna")
    public Set<Akses> getAkseses() {
        return this.akseses;
    }
    
    public void setAkseses(Set<Akses> akseses) {
        this.akseses = akseses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pengguna")
    public Set<Po> getPos() {
        return this.pos;
    }
    
    public void setPos(Set<Po> pos) {
        this.pos = pos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pengguna")
    public Set<Pesanan> getPesanans() {
        return this.pesanans;
    }
    
    public void setPesanans(Set<Pesanan> pesanans) {
        this.pesanans = pesanans;
    }




}


