package ta.util.orm.mapping;
// Generated Oct 20, 2013 5:25:45 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vendor generated by hbm2java
 */
@Entity
@Table(name="vendor"
    ,catalog="skripsi"
)
public class Vendor  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String kode;
     private String telepon;
     private String email;
     private String alamat;

    public Vendor() {
    }

    public Vendor(String nama, String kode, String telepon, String email, String alamat) {
       this.nama = nama;
       this.kode = kode;
       this.telepon = telepon;
       this.email = email;
       this.alamat = alamat;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nama", nullable=false, length=50)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    
    @Column(name="kode", nullable=false, length=5)
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    
    @Column(name="telepon", nullable=false, length=15)
    public String getTelepon() {
        return this.telepon;
    }
    
    public void setTelepon(String telepon) {
        this.telepon = telepon;
    }
    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="alamat", nullable=false, length=65535)
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


